### ISSUE TITLE
Auth::user() returns main auth user

### ISSUE THREAD

**Issue by projct1** [nckg/laravel-impersonate#1]
- Laravel Version: 5.4.33.

### Description:
After impersonating (with existing session key `impersonate`), `dump(Auth::user())` outputs main auth user.

**Comment by nckg** [comment]
Can you add some more details about this? I'm having some trouble replicating your issue.

**Comment by projct1** [comment]
Here is large description)
https://github.com/laravel/framework/issues/20722
